version: '3'

services:
  freeradius:
    # image: goofball222/freeradius
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freeradius
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./clients.conf:/etc/raddb/clients.conf
      - ./radiusd.conf:/etc/raddb/radiusd.conf
      - ./authorize:/etc/raddb/mods-config/files/authorize # login user account
      - ./default:/etc/raddb/sites-available/default  # for mac address auth or 802.1x
      - ./authorized_macs:/etc/raddb/authorized_macs  # accept mac address list
      - ./files:/etc/raddb/mods-available/files # set mac address list file
      - ./eap:/etc/raddb/mods-available/eap # eap config
#      - ./certs:/etc/freeradius/certs # do it by Dockerfile
    environment:
      - TZ=UTC
      - RADIUSD_OPTS=-xx # Enable this for FreeRadius extra log verbosity/degub

  freeradius-test:
    image: goofball222/freeradius
    container_name: freeradius-test
    network_mode: bridge
    depends_on:
      - freeradius
    links:
      - freeradius
        #    command: "radtest bob hello freeradius 0 testing123"
    command: "radtest bob hello freeradius 0 SECRET"
